services:
  fortytwo.practicaltest.api:
    image: fortytwo.practicaltest.api
    build:
      context: .
      dockerfile: src/Fortytwo.PracticalTest.Api/Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/practicaltest.db