services:
  fortytwo.practicaltest.api:
    image: fortytwo.practicaltest.api
    build:
      context: .
      dockerfile: src/Fortytwo.PracticalTest.Api/Dockerfile
  db:
    image: postgres:15
    container_name: practicaltest_pgsql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: practicaltest_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: